### ISSUE TITLE
Define DB Schema

### ISSUE THREAD

**Issue by maedae** [maedae/02-29-pair-project#1]
- [x] Get schema cleared by instructor.

**Comment by jeremystoll** [comment]
[Google Sheets Schema](https://docs.google.com/spreadsheets/d/1IKTO0uwm0PYmKCoLjq8eSn95D0Zk10e__bYUHViboXw/edit?usp=sharing)

**Comment by maedae** [comment]
require_relative "./_configure"

DB.define_table("users")
DB.define_column("users", "name", "string")
DB.define_column("users", "email", "string")
DB.define_column("users", "password", "string")
DB.define_column("users", "created_by", "integer")
DB.define_column("users", "updated_by", "integer")

DB.define_table("buildings")
DB.define_column("buildings", "address", "string")
DB.define_column("buildings", "user_id", "integer")
DB.define_column("buildings", "landlord_name", "string")
DB.define_column("buildings", "building_image", "string")
DB.define_column("buildings", "move_in", "date")
DB.define_column("buildings", "move_out", "date")
DB.define_column("buildings", "created_by", "integer")
DB.define_column("buildings", "updated_by", "integer")

DB.define_table("rooms")
DB.define_column("rooms", "title", "string")
DB.define_column("rooms", "room_image", "string")
DB.define_column("rooms", "building_id", "integer")
DB.define_column("rooms", "created_by", "integer")
DB.define_column("rooms", "updated_by", "integer")

DB.define_table("items")
DB.define_column("items", "title", "string")
DB.define_column("items", "description", "string")
DB.define_column("items", "room_id", "integer")
DB.define_column("items", "created_by", "integer")
DB.define_column("items", "updated_by", "integer") 

DB.define_table("photos")
DB.define_column("photos", "item_id", "string")
DB.define_column("photos", "image", "string")
DB.define_column("photos", "created_by", "integer")
DB.define_column("photos", "updated_by", "integer")

**Comment by sumeetjain** [comment]
Was this code implemented in a feature branch? It should have been. There should be _zero_ commits made to the master branch directly.

**Comment by sumeetjain** [comment]
Schema looks good, but please make sure you don't commit it within master.

**Comment by maedae** [comment]
It shouldn't have been committed. I just did git push so that the basic code would be available for Jeremy, 'cause we were confused why he wasn't getting anything when he cloned my repo.
