### ISSUE TITLE
Refactoring app/models/item.rb

### ISSUE THREAD

**Issue by maedae** [maedae/02-29-pair-project#36]
- [x] 1[67, 68]:DuplicateMethodCall: Item#find_and_delete_item_photos calls Photo.where({"item_id" => self.id}) 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [x]  2[67, 68]:DuplicateMethodCall: Item#find_and_delete_item_photos calls self.id 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [x] 3[47, 49, 51, 53, 55]:DuplicateMethodCall: Item#get_condition_tag calls self.condition 5 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [x] 4[77, 77]:DuplicateMethodCall: Item#get_created_by_user_info_for_item calls self.created_by 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [x] 5 [94, 94]:DuplicateMethodCall: Item#get_item_photos calls Photo.where({"item_id" => self.id}) 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [x]  6[94, 94]:DuplicateMethodCall: Item#get_item_photos calls self.id 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [x] 7[86, 86]:DuplicateMethodCall: Item#get_updated_by_user_info_for_item calls self.updated_by 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [x] 8[1]:IrresponsibleModule: Item has no descriptive comment [https://github.com/troessner/reek/blob/master/docs/Irresponsible-Module.md]
- [x] 9[77]:NilCheck: Item#get_created_by_user_info_for_item performs a nil-check [https://github.com/troessner/reek/blob/master/docs/Nil-Check.md]
- [x] 10[94]:NilCheck: Item#get_item_photos performs a nil-check [https://github.com/troessner/reek/blob/master/docs/Nil-Check.md]
- [x] 11[86]:NilCheck: Item#get_updated_by_user_info_for_item performs a nil-check [https://github.com/troessner/reek/blob/master/docs/Nil-Check.md]
- [x] 12[23]:TooManyStatements: Item#create_item_check_valid_action has approx 6 statements [https://github.com/troessner/reek/blob/master/docs/Too-Many-Statements.md]
- [x] 13[44]:TooManyStatements: Item#get_condition_tag has approx 7 statements [https://github.com/troessner/reek/blob/master/docs/Too-Many-Statements.md]

**Comment by jeremystoll** [comment]
If it's all the same to you, I can start here. Cutting a branch for refactoring-app-models-item #36 with your okay?

**Comment by jeremystoll** [comment]
[67, 68]:DuplicateMethodCall: Item#find_and_delete_item_photos calls Photo.where({"item_id" => self.id}) 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]

Refactored above, simplifying the method to define variable as Photo.where(...etc), then checking it for nil, and deleting it if not nil. This way, the "where" search happens only once.

**Comment by jeremystoll** [comment]
[67, 68]:DuplicateMethodCall: Item#find_and_delete_item_photos calls self.id 2 times 

Resolved as a result of previous fix.

**Comment by jeremystoll** [comment]
[47, 49, 51, 53, 55]:DuplicateMethodCall: Item#get_condition_tag calls self.condition 5 times 

Resolved by calling method once, setting the value to a variable then accessing that variable in subsequent lines.

**Comment by jeremystoll** [comment]
Working on:
[77, 77]:DuplicateMethodCall: Item#get_created_by_user_info_for_item calls self.created_by 2 times 

&

 [77]:NilCheck: Item#get_created_by_user_info_for_item performs a nil-check

**Comment by jeremystoll** [comment]
[77, 77]:DuplicateMethodCall: Item#get_created_by_user_info_for_item calls self.created_by 2 times
[77]:NilCheck: Item#get_created_by_user_info_for_item performs a nil-check
&
[86]:NilCheck: Item#get_updated_by_user_info_for_item performs a nil-check 

Resolved Duplicate Method Call by refactoring. Considering the event of a User being deleted and an Item remaining to be accessed by the deleted's housemate, it was determined that the nil-check was needed to avoid an error.

**Comment by jeremystoll** [comment]
Starting work on:

[94, 94]:DuplicateMethodCall: Item#get_item_photos calls Photo.where({"item_id" => self.id})
94, 94]:DuplicateMethodCall: Item#get_item_photos calls self.id 2 times 
&
[94]:NilCheck: Item#get_item_photos performs a nil-check

**Comment by jeremystoll** [comment]
Resolved line 94, and retained nil check without repeating method.

**Comment by jeremystoll** [comment]
Starting work on:
[1]:IrresponsibleModule: Item has no descriptive comment

**Comment by jeremystoll** [comment]
Starting work on:
[23]:TooManyStatements: Item#create_item_check_valid_action has approx 6 statements

**Comment by jeremystoll** [comment]
[23]:TooManyStatements: Item#create_item_check_valid_action has approx 6 statements

Resolved by breaking up method into 3 methods (title check, condition check, and initializing and returning the array with errors contained within. "message" variable changed to "@message", as a result. Tests passed with "@message" variable.

**Comment by jeremystoll** [comment]
13[44]:TooManyStatements: Item#get_condition_tag has approx 7 statements 

Resolved, split into 3 methods and changed the methodology to reference a hash to get the condition String (eg "Poor", "Damaged", etc), rather than a list of if/elsif. Merged with master
