### ISSUE TITLE
Refactoring app/models/photo.rb

### ISSUE THREAD

**Issue by maedae** [maedae/02-29-pair-project#37]
- [x] [1]:IrresponsibleModule: Photo has no descriptive comment [https://github.com/troessner/reek/blob/master/docs/Irresponsible-Module.md]

**Comment by jeremystoll** [comment]
[1]:IrresponsibleModule: Photo has no descriptive comment 

Starting work on this.

**Comment by jeremystoll** [comment]
[1]:IrresponsibleModule: Photo has no descriptive comment

Resolved (I am admittedly unsure if my explanation is complete and/or relevant). Also, I realized after merging my branch that I had neglected to make a pull request. All appears well with the world and our code.
