### ISSUE TITLE
Set Up User Authentication

### ISSUE THREAD

**Issue by maedae** [maedae/02-29-pair-project#4]
- [x] Add Account Creation Page
- [x] Add Sign-in page
- [x] add validation checks for name, email, password
- [x] Write tests for User Authentication (if necessary)

**Comment by sumeetjain** [comment]
User Dashboard should be its own Issue with details about what goes on it.

**Comment by sumeetjain** [comment]
"add *before controllers to each table's controller." should be its own Issue with details about what specifically will be restricted.

**Comment by sumeetjain** [comment]
What does this:

![](http://cl.ly/fIH4/Screen%20Shot%202016-03-01%20at%2011.39.58%20AM.png)

have to do with this issue?

**Comment by maedae** [comment]
we actually took that out and put it in the model. 
that was just us initially trying to get out ideas out there :D

**Comment by sumeetjain** [comment]
Only do the work needed for this issue in this feature's PR. Whether it's in the model and just for getting ideas out there is not a reason to build associations as part of this issue. Next time, please make a new issue that will add this functionality.

**Comment by maedae** [comment]
All right. we have tests written for the login. they they all pass. I am going to make another issue for the "Forgot Password" feature. is it okay we merge this branch to master and close this issue?
