### ISSUE TITLE
CRUD for Items table

### ISSUE THREAD

**Issue by maedae** [maedae/02-29-pair-project#5]
- [x]  C
  
  > - [x] text field for title
  > - [x] textarea for description 
  >   - [x] image uploaded. can save multiple photos
  > - [x] photos saved to Photo table. sets item id to item_id column. 
  > - [x] radio buttons for conditions
  >   - [x] button for "add another" && "finished" 
  > - [x] saving sets created_by to user's id
  > - [x] saving sets created_at to current time
  > - [x] "add another" does erb route back to item create page. displays notice that the previous item was added.
  > - [x] "finished" redirects to review page item
- [x]  R
  
  > - [x] displays all information set in created/updated pages. 
  > - [x] room name displayed at top of page. clickable hyperlink back to main room page. 
  > - [x] "update" and "delete" buttons for item on page.
  > - [x] created_at, created_by && updated_at, updated_by information displayed at bottom of page
- [x]  U
  
  > - [x] update text field for title - set to current info
  > - [x] update textarea for description - set to current info
  > - [x] add/delete images for item
  > - [x] update radio buttons for conditions
  > - [x] saving sets updated_by to user's id
  > - [x] saving sets updated_at to current time
- [x]  D
  
  > - [x] deleting item deletes row in database
  > - [x] deleting item deletes all images stored in Photos table with that item id set in item_id
  > - [x] deleting item does not affect other items for room, or parent room data. 
  > - [x] write tests when applicable.

**Comment by sumeetjain** [comment]
Tasks should be more specific and indicate actual features. E.g. for 'Rooms', you might have:
- List all damages for this room
- Deleting a room also deletes its damages
- etc.

**Comment by sumeetjain** [comment]
Break this up into multiple issues.
